/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ucundinamarca.principal;

import edu.ucundinamarca.core.Triangulo;
import edu.ucundinamarca.core.Cuadrado;
import edu.ucundinamarca.core.Rectangulo;
import javax.swing.JOptionPane;

/**
 *
 * @author YEISON
 */
public class FrameFigura extends javax.swing.JFrame {

    /**
     * Creates new form JFigura
     */
    public FrameFigura() {
        initComponents();
        this.setResizable(false);
        setLocationRelativeTo(null);
        setTitle("FIGURAS");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPanel = new javax.swing.JTabbedPane();
        panelCuadrado = new javax.swing.JPanel();
        txtCuadradoY3 = new javax.swing.JTextField();
        txtCuadradoX4 = new javax.swing.JTextField();
        txtCuadradoY4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtCuadradoX1 = new javax.swing.JTextField();
        txtCuadradoY1 = new javax.swing.JTextField();
        txtCuadradoX2 = new javax.swing.JTextField();
        txtCuadradoY2 = new javax.swing.JTextField();
        txtCuadradoX3 = new javax.swing.JTextField();
        pnlGraficaCuadrado = new javax.swing.JPanel();
        btnGraficarCuadrado = new javax.swing.JButton();
        lblPerimetroCuadrado = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        lblAreaCuadrado = new javax.swing.JLabel();
        colorCuadradoBox = new javax.swing.JComboBox();
        panelRectangulo = new javax.swing.JPanel();
        txtRectanguloY3 = new javax.swing.JTextField();
        txtRectanguloX4 = new javax.swing.JTextField();
        txtRectanguloY4 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtRectanguloX1 = new javax.swing.JTextField();
        txtRectanguloY1 = new javax.swing.JTextField();
        txtRectanguloX2 = new javax.swing.JTextField();
        txtRectanguloY2 = new javax.swing.JTextField();
        txtRectanguloX3 = new javax.swing.JTextField();
        pnlGraficaRectangulo = new javax.swing.JPanel();
        lblPerimetroRectangulo = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        lblAreaRectangulo = new javax.swing.JLabel();
        btnGraficarRectangulo = new javax.swing.JButton();
        colorRectanguloBox = new javax.swing.JComboBox();
        panelTriangulo = new javax.swing.JPanel();
        txtTrianguloY3 = new javax.swing.JTextField();
        pnlGraficaTriangulo = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtTrianguloX1 = new javax.swing.JTextField();
        txtTrianguloY1 = new javax.swing.JTextField();
        txtTrianguloX2 = new javax.swing.JTextField();
        txtTrianguloY2 = new javax.swing.JTextField();
        txtTrianguloX3 = new javax.swing.JTextField();
        perimetroTrianguloLabel = new javax.swing.JLabel();
        areaTrianguloLabel = new javax.swing.JLabel();
        btnGraficarTriangulo = new javax.swing.JButton();
        tipoTrianguloLabel = new javax.swing.JLabel();
        colorTrianguloBox = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(820, 620));

        txtCuadradoY3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCuadradoY3KeyTyped(evt);
            }
        });

        txtCuadradoX4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCuadradoX4KeyTyped(evt);
            }
        });

        txtCuadradoY4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCuadradoY4KeyTyped(evt);
            }
        });

        jLabel7.setText("   X");

        jLabel8.setText("   Y");

        jLabel9.setText("COORDENADA 1");

        jLabel10.setText("COORDENADA 2");

        jLabel11.setText("COORDENADA 4");

        jLabel12.setText("COORDENADA 3");

        txtCuadradoX1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtCuadradoX1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCuadradoX1KeyTyped(evt);
            }
        });

        txtCuadradoY1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCuadradoY1KeyTyped(evt);
            }
        });

        txtCuadradoX2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        txtCuadradoX2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCuadradoX2KeyTyped(evt);
            }
        });
        txtCuadradoX2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCuadradoX2KeyTyped(evt);
            }
        });

        txtCuadradoY2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCuadradoY2KeyTyped(evt);
            }
        });

        txtCuadradoX3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCuadradoX3KeyTyped(evt);
            }
        });

        pnlGraficaCuadrado.setBackground(new java.awt.Color(204, 255, 204));
        pnlGraficaCuadrado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        javax.swing.GroupLayout pnlGraficaCuadradoLayout = new javax.swing.GroupLayout(pnlGraficaCuadrado);
        pnlGraficaCuadrado.setLayout(pnlGraficaCuadradoLayout);
        pnlGraficaCuadradoLayout.setHorizontalGroup(
            pnlGraficaCuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 518, Short.MAX_VALUE)
        );
        pnlGraficaCuadradoLayout.setVerticalGroup(
            pnlGraficaCuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 518, Short.MAX_VALUE)
        );

        btnGraficarCuadrado.setText("GRAFICAR");
        btnGraficarCuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGraficarCuadradoActionPerformed(evt);
            }
        });

        jLabel19.setText("PERIMETRO");

        jLabel20.setText("AREA");

        colorCuadradoBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ROJO", "VERDE", "AZUL", "AMARILLO", "NEGRO", "NARANJA" }));

        javax.swing.GroupLayout panelCuadradoLayout = new javax.swing.GroupLayout(panelCuadrado);
        panelCuadrado.setLayout(panelCuadradoLayout);
        panelCuadradoLayout.setHorizontalGroup(
            panelCuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCuadradoLayout.createSequentialGroup()
                .addGroup(panelCuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCuadradoLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(panelCuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelCuadradoLayout.createSequentialGroup()
                                .addGroup(panelCuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelCuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblAreaCuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblPerimetroCuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panelCuadradoLayout.createSequentialGroup()
                                .addGroup(panelCuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(colorCuadradoBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panelCuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelCuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelCuadradoLayout.createSequentialGroup()
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelCuadradoLayout.createSequentialGroup()
                                        .addComponent(txtCuadradoX1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtCuadradoY1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelCuadradoLayout.createSequentialGroup()
                                        .addComponent(txtCuadradoX2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtCuadradoY2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelCuadradoLayout.createSequentialGroup()
                                        .addComponent(txtCuadradoX3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtCuadradoY3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelCuadradoLayout.createSequentialGroup()
                                        .addComponent(txtCuadradoX4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtCuadradoY4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(panelCuadradoLayout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(btnGraficarCuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(pnlGraficaCuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        panelCuadradoLayout.setVerticalGroup(
            panelCuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCuadradoLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(colorCuadradoBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCuadradoX1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCuadradoY1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCuadradoX2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCuadradoY2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCuadradoX3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCuadradoY3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCuadradoX4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCuadradoY4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(btnGraficarCuadrado)
                .addGap(36, 36, 36)
                .addGroup(panelCuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAreaCuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPerimetroCuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCuadradoLayout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(pnlGraficaCuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnlGraficaCuadrado.getAccessibleContext().setAccessibleDescription("");

        tabbedPanel.addTab("CUADRADO", panelCuadrado);

        txtRectanguloY3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRectanguloY3KeyTyped(evt);
            }
        });

        txtRectanguloX4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRectanguloX4KeyTyped(evt);
            }
        });

        txtRectanguloY4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRectanguloY4KeyTyped(evt);
            }
        });

        jLabel1.setText("   X");

        jLabel2.setText("   Y");

        jLabel3.setText("COORDENADA 1");

        jLabel4.setText("COORDENADA 2");

        jLabel5.setText("COORDENADA 4");

        jLabel6.setText("COORDENADA 3");

        txtRectanguloX1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRectanguloX1KeyTyped(evt);
            }
        });

        txtRectanguloY1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRectanguloY1KeyTyped(evt);
            }
        });

        txtRectanguloX2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRectanguloX2KeyTyped(evt);
            }
        });

        txtRectanguloY2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRectanguloY2KeyTyped(evt);
            }
        });

        txtRectanguloX3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRectanguloX3KeyTyped(evt);
            }
        });

        pnlGraficaRectangulo.setBackground(new java.awt.Color(204, 255, 204));
        pnlGraficaRectangulo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        pnlGraficaRectangulo.setPreferredSize(new java.awt.Dimension(520, 520));

        javax.swing.GroupLayout pnlGraficaRectanguloLayout = new javax.swing.GroupLayout(pnlGraficaRectangulo);
        pnlGraficaRectangulo.setLayout(pnlGraficaRectanguloLayout);
        pnlGraficaRectanguloLayout.setHorizontalGroup(
            pnlGraficaRectanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 518, Short.MAX_VALUE)
        );
        pnlGraficaRectanguloLayout.setVerticalGroup(
            pnlGraficaRectanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 518, Short.MAX_VALUE)
        );

        jLabel21.setText("PERIMETRO");

        jLabel22.setText("AREA");

        btnGraficarRectangulo.setText("GRAFICAR");
        btnGraficarRectangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGraficarRectanguloActionPerformed(evt);
            }
        });

        colorRectanguloBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ROJO", "VERDE", "AZUL", "AMARILLO", "NEGRO", "NARANJA" }));

        javax.swing.GroupLayout panelRectanguloLayout = new javax.swing.GroupLayout(panelRectangulo);
        panelRectangulo.setLayout(panelRectanguloLayout);
        panelRectanguloLayout.setHorizontalGroup(
            panelRectanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRectanguloLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(panelRectanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRectanguloLayout.createSequentialGroup()
                        .addGroup(panelRectanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelRectanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAreaRectangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPerimetroRectangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelRectanguloLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(btnGraficarRectangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelRectanguloLayout.createSequentialGroup()
                        .addGroup(panelRectanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(colorRectanguloBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelRectanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelRectanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelRectanguloLayout.createSequentialGroup()
                                .addComponent(txtRectanguloX2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtRectanguloY2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelRectanguloLayout.createSequentialGroup()
                                .addComponent(txtRectanguloX3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtRectanguloY3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelRectanguloLayout.createSequentialGroup()
                                .addComponent(txtRectanguloX4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtRectanguloY4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelRectanguloLayout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelRectanguloLayout.createSequentialGroup()
                                .addComponent(txtRectanguloX1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtRectanguloY1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addComponent(pnlGraficaRectangulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        panelRectanguloLayout.setVerticalGroup(
            panelRectanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRectanguloLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(colorRectanguloBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRectanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRectanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRectanguloX1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRectanguloY1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRectanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRectanguloX2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRectanguloY2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRectanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRectanguloX3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRectanguloY3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRectanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRectanguloX4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRectanguloY4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(btnGraficarRectangulo)
                .addGap(36, 36, 36)
                .addGroup(panelRectanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAreaRectangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRectanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPerimetroRectangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(208, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRectanguloLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlGraficaRectangulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tabbedPanel.addTab("RECTANGULO", panelRectangulo);

        txtTrianguloY3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTrianguloY3KeyTyped(evt);
            }
        });

        pnlGraficaTriangulo.setBackground(new java.awt.Color(204, 255, 204));
        pnlGraficaTriangulo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        pnlGraficaTriangulo.setPreferredSize(new java.awt.Dimension(520, 520));

        javax.swing.GroupLayout pnlGraficaTrianguloLayout = new javax.swing.GroupLayout(pnlGraficaTriangulo);
        pnlGraficaTriangulo.setLayout(pnlGraficaTrianguloLayout);
        pnlGraficaTrianguloLayout.setHorizontalGroup(
            pnlGraficaTrianguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 518, Short.MAX_VALUE)
        );
        pnlGraficaTrianguloLayout.setVerticalGroup(
            pnlGraficaTrianguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 518, Short.MAX_VALUE)
        );

        jLabel13.setText("   X");

        jLabel14.setText("   Y");

        jLabel15.setText("COORDENADA 1");

        jLabel16.setText("COORDENADA 2");

        jLabel18.setText("COORDENADA 3");

        txtTrianguloX1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTrianguloX1KeyTyped(evt);
            }
        });

        txtTrianguloY1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTrianguloY1KeyTyped(evt);
            }
        });

        txtTrianguloX2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTrianguloX2KeyTyped(evt);
            }
        });

        txtTrianguloY2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTrianguloY2KeyTyped(evt);
            }
        });

        txtTrianguloX3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTrianguloX3KeyTyped(evt);
            }
        });

        perimetroTrianguloLabel.setText("PERIMETRO:");

        areaTrianguloLabel.setText("AREA:");

        btnGraficarTriangulo.setText("GRAFICAR");
        btnGraficarTriangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGraficarTrianguloActionPerformed(evt);
            }
        });

        tipoTrianguloLabel.setText("TIPO:");

        colorTrianguloBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ROJO", "VERDE", "AZUL", "AMARILLO", "NEGRO", "NARANJA" }));

        javax.swing.GroupLayout panelTrianguloLayout = new javax.swing.GroupLayout(panelTriangulo);
        panelTriangulo.setLayout(panelTrianguloLayout);
        panelTrianguloLayout.setHorizontalGroup(
            panelTrianguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTrianguloLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(panelTrianguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTrianguloLayout.createSequentialGroup()
                        .addGroup(panelTrianguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(colorTrianguloBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelTrianguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelTrianguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelTrianguloLayout.createSequentialGroup()
                                .addComponent(txtTrianguloX2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTrianguloY2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelTrianguloLayout.createSequentialGroup()
                                .addComponent(txtTrianguloX3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTrianguloY3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelTrianguloLayout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelTrianguloLayout.createSequentialGroup()
                                .addComponent(txtTrianguloX1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTrianguloY1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelTrianguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(tipoTrianguloLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(perimetroTrianguloLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(areaTrianguloLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelTrianguloLayout.createSequentialGroup()
                            .addGap(46, 46, 46)
                            .addComponent(btnGraficarTriangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(pnlGraficaTriangulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        panelTrianguloLayout.setVerticalGroup(
            panelTrianguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTrianguloLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(colorTrianguloBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelTrianguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelTrianguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTrianguloX1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTrianguloY1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelTrianguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTrianguloX2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTrianguloY2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelTrianguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTrianguloX3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTrianguloY3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(btnGraficarTriangulo)
                .addGap(36, 36, 36)
                .addComponent(areaTrianguloLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(perimetroTrianguloLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tipoTrianguloLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(200, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTrianguloLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlGraficaTriangulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tabbedPanel.addTab("TRIANGULO", panelTriangulo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPanel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabbedPanel))
        );

        tabbedPanel.getAccessibleContext().setAccessibleName("TRIANGULO");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGraficarCuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGraficarCuadradoActionPerformed
        this.graficarPlanoCartesianoCuadro();
        if (this.validarCamposLlenosCuadrado() == true) {
            byte[] coordenada1 = {Byte.parseByte(txtCuadradoX1.getText()), Byte.parseByte(txtCuadradoY1.getText())};
            byte[] coordenada2 = {Byte.parseByte(txtCuadradoX2.getText()), Byte.parseByte(txtCuadradoY2.getText())};
            byte[] coordenada3 = {Byte.parseByte(txtCuadradoX3.getText()), Byte.parseByte(txtCuadradoY3.getText())};
            byte[] coordenada4 = {Byte.parseByte(txtCuadradoX4.getText()), Byte.parseByte(txtCuadradoY4.getText())};

            Cuadrado cuadrado = new Cuadrado(coordenada1, coordenada2, coordenada3, coordenada4, colorCuadradoBox.getSelectedItem().toString());
            if (cuadrado.validarCoordenadas(coordenada1, coordenada2, coordenada3, coordenada4) == true) {
                cuadrado.trazarFigura(pnlGraficaCuadrado.getGraphics(), coordenada1, coordenada2, coordenada3, coordenada4);
                cuadrado.calcularLado1(coordenada1, coordenada2);
                //Se halla el Area y el perimetro
                lblAreaCuadrado.setText(cuadrado.hallarArea() + "");
                lblPerimetroCuadrado.setText(cuadrado.hallarPerimetro() + "");

                //panelCuadrado.repaint();
                //pnlGraficaCuadrado.repaint();
            } else {
                JOptionPane.showMessageDialog(panelCuadrado, "COORDENADAS INCORRECTAS, VERIFIQUE E INTENTE NUEVAMENTE", "MENSAJE DEL SISTEMA",
                        JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(panelCuadrado, "DILIGENCIE TODOS LOS CAMPOS", "MENSAJE DEL SISTEMA",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGraficarCuadradoActionPerformed

    private void graficarPlanoCartesianoCuadro() {
        // TODO add your handling code here:
        //Dibuja los ejes del plano
        pnlGraficaCuadrado.getGraphics().drawLine(10, 10, 10, 510);
        pnlGraficaCuadrado.getGraphics().drawLine(10, 510, 510, 510);
        //Dibuja las flechas del plano
        pnlGraficaCuadrado.getGraphics().drawLine(10, 0, 15, 5);
        pnlGraficaCuadrado.getGraphics().drawLine(10, 0, 5, 5);
        pnlGraficaCuadrado.getGraphics().drawLine(520, 510, 515, 505);
        pnlGraficaCuadrado.getGraphics().drawLine(520, 510, 515, 515);
        //Dibuja la escala del plano cartesiano
        for (int i = 1; i <= 10; i++) {
            if (i == 1) {

                pnlGraficaCuadrado.getGraphics().drawLine(0, 10, 20, 10);
            }
            if (i != 10) {
                pnlGraficaCuadrado.getGraphics().drawLine(0, (50 * i) + 10, 20, (50 * i) + 10);
            }
            pnlGraficaCuadrado.getGraphics().drawLine((50 * i) + 10, 500, (50 * i) + 10, 520);
        }

    }

    private void btnGraficarRectanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGraficarRectanguloActionPerformed

        if (this.validarCamposLlenosRectangulo()) {
            byte[] coordenada1 = {Byte.parseByte(txtRectanguloX1.getText()), Byte.parseByte(txtRectanguloY1.getText())};
            byte[] coordenada2 = {Byte.parseByte(txtRectanguloX2.getText()), Byte.parseByte(txtRectanguloY2.getText())};
            byte[] coordenada3 = {Byte.parseByte(txtRectanguloX3.getText()), Byte.parseByte(txtRectanguloY3.getText())};
            byte[] coordenada4 = {Byte.parseByte(txtRectanguloX4.getText()), Byte.parseByte(txtRectanguloY4.getText())};

            Rectangulo rectangulo = new Rectangulo(coordenada1, coordenada2, coordenada3, coordenada4, colorRectanguloBox.getSelectedItem().toString());

            if (rectangulo.validarCoordenadas(coordenada1, coordenada2, coordenada3, coordenada4) == true) {
                rectangulo.trazarFigura(pnlGraficaRectangulo.getGraphics(), coordenada1, coordenada2, coordenada3, coordenada4);
                rectangulo.calcularLado1(coordenada1, coordenada2);
                rectangulo.calcularLado2(coordenada2, coordenada3);
                //Se halla el Area y el perimetro
                lblAreaRectangulo.setText(rectangulo.hallarArea() + "");
                lblPerimetroRectangulo.setText(rectangulo.hallarPerimetro() + "");
            } else {
                JOptionPane.showMessageDialog(panelRectangulo, "COORDENADAS INCORRECTAS, VERIFIQUE E INTENTE NUEVAMENTE", "MENSAJE DEL SISTEMA",
                        JOptionPane.ERROR_MESSAGE);
            }

        } else {
            JOptionPane.showMessageDialog(panelRectangulo, "DILIGENCIE TODOS LOS CAMPOS", "MENSAJE DEL SISTEMA",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGraficarRectanguloActionPerformed

    private void graficarPlanoCartesianoRectangulo() {
        //Dibuja los ejes del plano
        pnlGraficaRectangulo.getGraphics().drawLine(10, 10, 10, 510);
        pnlGraficaRectangulo.getGraphics().drawLine(10, 510, 510, 510);
        //Dibuja las flechas del plano
        pnlGraficaRectangulo.getGraphics().drawLine(10, 0, 15, 5);
        pnlGraficaRectangulo.getGraphics().drawLine(10, 0, 5, 5);
        pnlGraficaRectangulo.getGraphics().drawLine(520, 510, 515, 505);
        pnlGraficaRectangulo.getGraphics().drawLine(520, 510, 515, 515);

        //Dibuja la escala del plano cartesiano
        for (int i = 1; i <= 10; i++) {
            if (i == 1) {
                pnlGraficaRectangulo.getGraphics().drawLine(0, 10, 20, 10);
            }
            pnlGraficaRectangulo.getGraphics().drawLine((50 * i) + 10, 500, (50 * i) + 10, 520);
            pnlGraficaRectangulo.getGraphics().drawLine(0, (50 * i) + 10, 20, (50 * i) + 10);
        }
    }

    private void btnGraficarTrianguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGraficarTrianguloActionPerformed

        if (this.validarCamposLlenosTriangulo()) {
            byte[] coordenada1 = {Byte.parseByte(txtTrianguloX1.getText()), Byte.parseByte(txtTrianguloY1.getText())};
            byte[] coordenada2 = {Byte.parseByte(txtTrianguloX2.getText()), Byte.parseByte(txtTrianguloY2.getText())};
            byte[] coordenada3 = {Byte.parseByte(txtTrianguloX3.getText()), Byte.parseByte(txtTrianguloY3.getText())};
            Triangulo triangulo = new Triangulo(coordenada1, coordenada2, coordenada3, colorTrianguloBox.getSelectedItem().toString());

            if (triangulo.validarCoordenadas(coordenada1, coordenada2, coordenada3)) {
                triangulo.trazarFigura(pnlGraficaTriangulo.getGraphics(), coordenada1, coordenada2, coordenada3);
                triangulo.definirTipo(coordenada1, coordenada2, coordenada3);
                triangulo.hallarBase(triangulo.getLado1(), triangulo.getLado2(), triangulo.getLado3(), triangulo.getTipo());
                triangulo.hallarAltura(triangulo.getLado1(), triangulo.getLado2(), triangulo.getLado3(), triangulo.getTipo());
                triangulo.hallarArea(triangulo.getBase(), triangulo.getAltura());
                triangulo.hallarPerimetro(triangulo.getLado1(), triangulo.getLado2(), triangulo.getLado3());

                areaTrianguloLabel.setText(areaTrianguloLabel.getText() + " " + triangulo.getArea());
                perimetroTrianguloLabel.setText(perimetroTrianguloLabel.getText() + " " + triangulo.getPerimetro());
                tipoTrianguloLabel.setText(tipoTrianguloLabel.getText() + " " + triangulo.getTipo());
            } else {
                JOptionPane.showMessageDialog(panelTriangulo, "COORDENADAS SIN COHERENCIA PARA UN TRIANGULO", "MENSAJE DEL SISTEMA",
                        JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(panelTriangulo, "DILIGENCIE TODOS LOS CAMPOS", "MENSAJE DEL SISTEMA",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGraficarTrianguloActionPerformed

    private void graficarPlanoCartesianoTriangulo() {
        areaTrianguloLabel.setText("AREA:");
        perimetroTrianguloLabel.setText("PERIMETRO:");
        tipoTrianguloLabel.setText("TIPO:");
        //Dibuja los ejes del plano
        pnlGraficaTriangulo.getGraphics().drawLine(10, 10, 10, 510);
        pnlGraficaTriangulo.getGraphics().drawLine(10, 510, 510, 510);
        //Dibuja las flechas del plano
        pnlGraficaTriangulo.getGraphics().drawLine(10, 0, 15, 5);
        pnlGraficaTriangulo.getGraphics().drawLine(10, 0, 5, 5);
        pnlGraficaTriangulo.getGraphics().drawLine(520, 510, 515, 505);
        pnlGraficaTriangulo.getGraphics().drawLine(520, 510, 515, 515);

        for (int i = 1; i <= 10; i++) {
            if (i == 1) {
                pnlGraficaTriangulo.getGraphics().drawLine(0, 10, 20, 10);

            }
            pnlGraficaTriangulo.getGraphics().drawLine((50 * i) + 10, 500, (50 * i) + 10, 520);
            pnlGraficaTriangulo.getGraphics().drawLine(0, (50 * i) + 10, 20, (50 * i) + 10);
        }
    }

    private Boolean validarCamposLlenosTriangulo() {

        if (txtTrianguloX1.getText().trim().length() == 0
                || txtTrianguloX2.getText().trim().length() == 0
                || txtTrianguloX3.getText().trim().length() == 0
                || txtTrianguloY1.getText().trim().length() == 0
                || txtTrianguloY2.getText().trim().length() == 0
                || txtTrianguloY3.getText().trim().length() == 0) {
            return false;
        } else {
            return true;
        }
    }

    private Boolean validarCamposLlenosCuadrado() {

        if (txtCuadradoX1.getText().trim().length() == 0
                || txtCuadradoX2.getText().trim().length() == 0
                || txtCuadradoX3.getText().trim().length() == 0
                || txtCuadradoX4.getText().trim().length() == 0
                || txtCuadradoY1.getText().trim().length() == 0
                || txtCuadradoY2.getText().trim().length() == 0
                || txtCuadradoY3.getText().trim().length() == 0
                || txtCuadradoY4.getText().trim().length() == 0) {
            return false;
        } else {
            return true;
        }
    }

    private Boolean validarCamposLlenosRectangulo() {

        if (txtRectanguloX1.getText().trim().length() == 0
                || txtRectanguloX2.getText().trim().length() == 0
                || txtRectanguloX3.getText().trim().length() == 0
                || txtRectanguloX4.getText().trim().length() == 0
                || txtRectanguloY1.getText().trim().length() == 0
                || txtRectanguloY2.getText().trim().length() == 0
                || txtRectanguloY3.getText().trim().length() == 0
                || txtRectanguloY4.getText().trim().length() == 0) {
            return false;
        } else {
            return true;
        }
    }

    private void validarCampos(java.awt.event.KeyEvent evt, javax.swing.JTextField text) {
        char caracter = evt.getKeyChar();
        //Validar que no sea una letra o , o .
        if (Character.isLetter(caracter) == true || caracter == '.' || caracter == ',') {
            //El caracter pulsado se rechaza
            evt.consume();
            JOptionPane.showMessageDialog(panelTriangulo, "DILIGENCIE SOLO NUMEROS ENTEROS ENTRE 1 Y 10 ", "MENSAJE DEL SISTEMA",
                    JOptionPane.ERROR_MESSAGE);

        }
        try {
            if (caracter != evt.VK_BACK_SPACE && caracter != evt.VK_ENTER && Integer.parseInt(text.getText() + caracter) > 10) {
                evt.consume();
                JOptionPane.showMessageDialog(panelTriangulo, "DILIGENCIE SOLO NUMEROS ENTEROS ENTRE 1 Y 10", "MENSAJE DEL SISTEMA",
                        JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(panelTriangulo, "DILIGENCIE SOLO NUMEROS ENTEROS ENTRE 1 Y 10", "MENSAJE DEL SISTEMA",
                    JOptionPane.ERROR_MESSAGE);
        }
        //Validar que sea un numero entre 1 y 10

    }

    private void txtCuadradoX1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCuadradoX1KeyTyped

        this.validarCampos(evt, txtCuadradoX1);
    }//GEN-LAST:event_txtCuadradoX1KeyTyped

    private void txtCuadradoX2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCuadradoX2KeyTyped
        // TODO add your handling code here:
        this.validarCampos(evt, txtCuadradoX2);
    }//GEN-LAST:event_txtCuadradoX2KeyTyped

    private void txtCuadradoX3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCuadradoX3KeyTyped
        // TODO add your handling code here:
        this.validarCampos(evt, txtCuadradoX3);
    }//GEN-LAST:event_txtCuadradoX3KeyTyped

    private void txtCuadradoX4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCuadradoX4KeyTyped
        // TODO add your handling code here:
        this.validarCampos(evt, txtCuadradoX4);
    }//GEN-LAST:event_txtCuadradoX4KeyTyped

    private void txtCuadradoY1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCuadradoY1KeyTyped
        // TODO add your handling code here:
        this.validarCampos(evt, txtCuadradoY1);
    }//GEN-LAST:event_txtCuadradoY1KeyTyped

    private void txtCuadradoY2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCuadradoY2KeyTyped
        // TODO add your handling code here:
        this.validarCampos(evt, txtCuadradoY2);
    }//GEN-LAST:event_txtCuadradoY2KeyTyped

    private void txtCuadradoY3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCuadradoY3KeyTyped
        // TODO add your handling code here:
        this.validarCampos(evt, txtCuadradoY3);
    }//GEN-LAST:event_txtCuadradoY3KeyTyped

    private void txtCuadradoY4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCuadradoY4KeyTyped
        // TODO add your handling code here:
        this.validarCampos(evt, txtCuadradoY4);
    }//GEN-LAST:event_txtCuadradoY4KeyTyped

    private void txtRectanguloX1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRectanguloX1KeyTyped
        this.validarCampos(evt, txtRectanguloX1);
    }//GEN-LAST:event_txtRectanguloX1KeyTyped

    private void txtRectanguloX2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRectanguloX2KeyTyped
        // TODO add your handling code here:
        this.validarCampos(evt, txtRectanguloX2);
    }//GEN-LAST:event_txtRectanguloX2KeyTyped

    private void txtRectanguloX3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRectanguloX3KeyTyped
        // TODO add your handling code here:
        this.validarCampos(evt, txtRectanguloX3);
    }//GEN-LAST:event_txtRectanguloX3KeyTyped

    private void txtRectanguloX4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRectanguloX4KeyTyped
        // TODO add your handling code here:
        this.validarCampos(evt, txtRectanguloX4);
    }//GEN-LAST:event_txtRectanguloX4KeyTyped

    private void txtRectanguloY1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRectanguloY1KeyTyped
        // TODO add your handling code here:
        this.validarCampos(evt, txtRectanguloY1);
    }//GEN-LAST:event_txtRectanguloY1KeyTyped

    private void txtRectanguloY2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRectanguloY2KeyTyped
        // TODO add your handling code here:
        this.validarCampos(evt, txtRectanguloY2);
    }//GEN-LAST:event_txtRectanguloY2KeyTyped

    private void txtRectanguloY3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRectanguloY3KeyTyped
        // TODO add your handling code here:
        this.validarCampos(evt, txtRectanguloY3);
    }//GEN-LAST:event_txtRectanguloY3KeyTyped

    private void txtRectanguloY4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRectanguloY4KeyTyped
        // TODO add your handling code here:
        this.validarCampos(evt, txtRectanguloY4);
    }//GEN-LAST:event_txtRectanguloY4KeyTyped

    private void txtTrianguloX1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTrianguloX1KeyTyped
        // TODO add your handling code here:
        this.validarCampos(evt, txtTrianguloX1);
    }//GEN-LAST:event_txtTrianguloX1KeyTyped

    private void txtTrianguloX2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTrianguloX2KeyTyped
        // TODO add your handling code here:
        this.validarCampos(evt, txtTrianguloX2);
    }//GEN-LAST:event_txtTrianguloX2KeyTyped

    private void txtTrianguloX3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTrianguloX3KeyTyped
        // TODO add your handling code here:
        this.validarCampos(evt, txtTrianguloX3);
    }//GEN-LAST:event_txtTrianguloX3KeyTyped

    private void txtTrianguloY1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTrianguloY1KeyTyped
        // TODO add your handling code here:
        this.validarCampos(evt, txtTrianguloY1);
    }//GEN-LAST:event_txtTrianguloY1KeyTyped

    private void txtTrianguloY2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTrianguloY2KeyTyped
        // TODO add your handling code here:
        this.validarCampos(evt, txtTrianguloY2);
    }//GEN-LAST:event_txtTrianguloY2KeyTyped

    private void txtTrianguloY3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTrianguloY3KeyTyped
        // TODO add your handling code here:
        this.validarCampos(evt, txtTrianguloY3);
    }//GEN-LAST:event_txtTrianguloY3KeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel areaTrianguloLabel;
    private javax.swing.JButton btnGraficarCuadrado;
    private javax.swing.JButton btnGraficarRectangulo;
    private javax.swing.JButton btnGraficarTriangulo;
    private javax.swing.JComboBox colorCuadradoBox;
    private javax.swing.JComboBox colorRectanguloBox;
    private javax.swing.JComboBox colorTrianguloBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblAreaCuadrado;
    private javax.swing.JLabel lblAreaRectangulo;
    private javax.swing.JLabel lblPerimetroCuadrado;
    private javax.swing.JLabel lblPerimetroRectangulo;
    private javax.swing.JPanel panelCuadrado;
    private javax.swing.JPanel panelRectangulo;
    private javax.swing.JPanel panelTriangulo;
    private javax.swing.JLabel perimetroTrianguloLabel;
    private javax.swing.JPanel pnlGraficaCuadrado;
    private javax.swing.JPanel pnlGraficaRectangulo;
    private javax.swing.JPanel pnlGraficaTriangulo;
    private javax.swing.JTabbedPane tabbedPanel;
    private javax.swing.JLabel tipoTrianguloLabel;
    private javax.swing.JTextField txtCuadradoX1;
    private javax.swing.JTextField txtCuadradoX2;
    private javax.swing.JTextField txtCuadradoX3;
    private javax.swing.JTextField txtCuadradoX4;
    private javax.swing.JTextField txtCuadradoY1;
    private javax.swing.JTextField txtCuadradoY2;
    private javax.swing.JTextField txtCuadradoY3;
    private javax.swing.JTextField txtCuadradoY4;
    private javax.swing.JTextField txtRectanguloX1;
    private javax.swing.JTextField txtRectanguloX2;
    private javax.swing.JTextField txtRectanguloX3;
    private javax.swing.JTextField txtRectanguloX4;
    private javax.swing.JTextField txtRectanguloY1;
    private javax.swing.JTextField txtRectanguloY2;
    private javax.swing.JTextField txtRectanguloY3;
    private javax.swing.JTextField txtRectanguloY4;
    private javax.swing.JTextField txtTrianguloX1;
    private javax.swing.JTextField txtTrianguloX2;
    private javax.swing.JTextField txtTrianguloX3;
    private javax.swing.JTextField txtTrianguloY1;
    private javax.swing.JTextField txtTrianguloY2;
    private javax.swing.JTextField txtTrianguloY3;
    // End of variables declaration//GEN-END:variables
}
